# Generated by Django 6.1 on 2026-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="ID чата Telegram"
            ),
        ),
    ]
