# Generated by Django 6.1 on 2026-08-24 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255, verbose_name="Place")),
                ("time", models.TimeField(verbose_name="Time")),
                ("action", models.CharField(max_length=255, verbose_name="Action")),
                (
                    "is_pleasant",
                    models.BooleanField(default=False, verbose_name="Is Pleasant"),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(default=1, verbose_name="Frequency"),
                ),
                (
                    "reward",
                    models.CharField(blank=True, max_length=255, verbose_name="Reward"),
                ),
                ("duration", models.PositiveIntegerField(verbose_name="Duration")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Is Public"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="useful_habits",
                        to="habits.habit",
                        verbose_name="Related Habit",
                    ),
                ),
            ],
        ),
    ]
