# Generated by Django 6.1 on 2026-08-24 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(max_length=255, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(verbose_name="Время на выполнение"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(default=1, verbose_name="Периодичность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False, verbose_name="Признак приятной привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="Признак публичности"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(max_length=255, verbose_name="Место"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="useful_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Вознаграждение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Время"),
        ),
    ]
