# Generated by Django 6.1 on 2026-08-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options_alter_habit_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notification_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее напоминание"
            ),
        ),
    ]
